---
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: ABank API - Accounts
paths:
  /accounts:
    get:
      summary: All Customer Accounts
      description: List of all customer accounts
      responses:    
        200:
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref : "https://raw.githubusercontent.com/akhapre/openapidemo/master/bankingApiComponents/accounts_schema.yaml#/components/schemas/Account"
              example: {"a":"b"}
                  
        401:
          $ref: "https://raw.githubusercontent.com/akhapre/openapidemo/master/bankingApiPathItems/base_path.yaml#/paths/~1base_path/get/responses/401"
        500:
          $ref: "https://raw.githubusercontent.com/akhapre/openapidemo/master/bankingApiPathItems/base_path.yaml#/paths/~1base_path/get/responses/401"
          
